// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`

  GET_ACTIVITY_REQUEST
  GET_ACTIVITY_SUCCESS
  GET_ACTIVITY_FAILURE

  UPDATE_ACTIVITY_REQUEST
  UPDATE_ACTIVITY_SUCCESS
  UPDATE_ACTIVITY_FAILURE 

  ADD_ACTIVITY_REQUEST
  ADD_ACTIVITY_SUCCESS
  ADD_ACTIVITY_FAILURE

  DELETE_ACTIVITY_REQUEST
  DELETE_ACTIVITY_SUCCESS
  DELETE_ACTIVITY_FAILURE
  
`)
